routes/frontend.php
<?php

use App\Http\Controllers\Frontend\CompareController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Frontend Table Routes
|--------------------------------------------------------------------------
*/

//HomePage
Route::get('lang/set', [App\Http\Controllers\LocalizationController::class, 'languageChange'])->name('setLanguage');

Route::get('/', [App\Http\Controllers\FrontendController::class, 'home'])->name('frontend.home');
Route::get('/calculator', [App\Http\Controllers\FrontendController::class, 'calculatorScreen'])->name('home.calculator');
//age
Route::post('/benefit', [App\Http\Controllers\FrontendController::class, 'benefits'])->name('home.benefits');

Route::post('/compare', [App\Http\Controllers\FrontendController::class, 'compareScreen'])->name('home.compare');
Route::get('/about', [App\Http\Controllers\FrontendController::class, 'about'])->name('frontend.about');

Route::get('/confirmation/{age}/{term}/{sum}/{mop}/{product}', [App\Http\Controllers\FrontendController::class, 'confirm'])->name('front.confirmation');

Route::post('corporateStore',[App\Http\Controllers\FrontendController::class,'corporateStore'])->name('lead.corporate');

Route::post('/confirm', [App\Http\Controllers\CalculationController::class, 'selectedPlanCalculation'])->name('front.confirm');

Route::get('get/cat/featureList', [App\Http\Controllers\FrontendController::class, 'findcatFeature'])->name('admin.get.category.feature');

Route::post('/plan/selected', [App\Http\Controllers\PlanselectedController::class, 'store'])->name('plan.selected');

Route::post('/plan/status/change', [App\Http\Controllers\PlanselectedController::class, 'updateStatus'])->name('plan.status.change');

//Route::get('/compare/result/demo',[App\Http\Controllers\FrontendController::class,'compareResult'])->name('compare.result.demo');

Route::post('frontend/add/lead', [App\Http\Controllers\Frontend\CompareController::class, 'leadCreate'])->name('frontend.add.lead');

Route::get('term-condition',[App\Http\Controllers\FrontendController::class,'termcondition'])->name('frontend.termcondition');
Route::get('privacy-policy',[App\Http\Controllers\FrontendController::class,'privacyPolicy'])->name('frontend.privacyPolicy');

Route::get('all/blogs',[App\Http\Controllers\FrontendController::class,'blogs'])->name('frontend.blogs');
Route::get('blog/{slug}',[App\Http\Controllers\FrontendController::class,'blogView'])->name('frontend.blog.view');

//contact
Route::get('contact', [App\Http\Controllers\FrontendController::class, 'contact'])->name('contact');
Route::post('contact', [App\Http\Controllers\FrontendController::class, 'contactStore'])->name('contact.message');

/**
 * Non-life Insurance Calculation
 */
Route::prefix('Nonlifeinsurance/calculator')->group(function () {
    Route::get('bike', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'nonlifecalculationForm']) ->name('frontend.nonlife.insurance');
    Route::post('motor', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'calculationMotor'])->name('frontend.nonlife.insurance.bike.calculation');
    Route::get('motors', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'calculationMotorview'])->name('frontend.nonlife.insurance.bike.view');
    Route::get('nonlife/detail', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'nonlifedetail'])->name('fronted.nonlife.details');
    Route::get('payment-view', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'paymentview'])->name('fronted.nonlife.payment');
    Route::post('motor/detail', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'detailmotor'])->name('fronted.bike.details');
    Route::post('/choosecustomer', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'choosecustomer'])->name('bike.customer.choose');
    Route::post('compulsary-excess', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'compulsaryExcess'])->name('motor.first.party.compulsary.excess');
    Route::post('excess-damage', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'excessDamage'])->name('bike.excess.damage');
    Route::post('manufacture-model', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'getModel'])->name('motor.first.party.model.manufacture');
    Route::post('make-draft-policy', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'makeDraftPolicy'])->name('construct.draft.policy');
    Route::get('make-policy', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'makeOnlinePolicy'])->name('motor.construct.policy');
    Route::get('/privatecar', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'carCalculator'])->name('private.car.nonlifeinsurance');
    Route::get('commerical-car', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'commercialCarCalculator'])->name('commerical.car.calculator.nonlifeinsurance');
    Route::get('invoice-pdf', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'loadPdf'])->name('pdf.invoice');
    // After KYC
    Route::post('motor-payment', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'paymentBikeFirstParty'])->name('motor.first.party.payment');
    Route::post('compulsary-excess', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'compulsaryExcess'])->name('bike.first.party.compulsary.excess');
    Route::post('excess-damage', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'excessDamage'])->name('motor.excess.damage');
    Route::get('policy-done', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'policyDone'])->name('policy.done');
    // Route::get('policy-view', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'viewPolicy'])->name('policy.detail.view');
    Route::get('draft-policy-view', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'viewDraftPolicy'])->name('policy.draft.view');
    Route::get('successfull/imepay', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'imePaySuccess'])->name('successfull.imepay');
    Route::get('unsuccessfull/imepay', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'imePayCancel'])->name('canceled.imepay');
    // Route::post('category-type', [App\Http\Controllers\Fronted\NonLifeCalculatorController::class, 'getCatType'])->name('bike.category.type');
    Route::get('debit-note', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'getDebitNote'])->name('bike.get.debit.note');
});

/**
 * Compare Routes
 */
Route::prefix('compare')
    ->name('compare.')
    ->group(function () {
        Route::get('', [CompareController::class, 'showCompareForm'])->name('form');
//        Route::post('result', [CompareController::class, 'compare'])->name('result');
        Route::post('viewplan',[CompareController::class,'viewPlan'])->name('viewplan');
        Route::post('result', [\App\Http\Controllers\CalculationController::class, 'frontendCompare'])->name('result');
    });

routes/web.php
        Route::resource('age-difference', \App\Http\Controllers\CoupleAgeDifferenceController::class);
//    Policy Paying Term Routes
        Route::resource('paying-term', \App\Http\Controllers\PayingTermController::class);
//  Api Key Routes
        Route::resource('api-key', \App\Http\Controllers\ApiKeyController::class);
        // Feature Routes
        Route::get('get/featureList', [App\Http\Controllers\LifeCalculatorController::class, 'findFeature'])->name('get.feature.list');

        Route::get('featureList', [App\Http\Controllers\FeatureController::class, 'index'])->name('feature.list');
        Route::get('featureList', [App\Http\Controllers\FeatureController::class, 'index'])->name('feature.list');
        Route::get('featureList', [App\Http\Controllers\FeatureController::class, 'index'])->name('feature.list');
        Route::get('featureCreate', [App\Http\Controllers\FeatureController::class, 'create'])->name('feature.create');
        Route::post('featureCreate', [App\Http\Controllers\FeatureController::class, 'store'])->name('feature.store');
        Route::get('featureEdit/{id}', [App\Http\Controllers\FeatureController::class, 'edit'])->name('feature.edit');
        Route::post('featureEdit/{id}', [App\Http\Controllers\FeatureController::class, 'update'])->name('feature.update');
        Route::delete('featureList/{id}', [App\Http\Controllers\FeatureController::class, 'destroy'])->name('feature.destroy');

        Route::get('featureproductList', [App\Http\Controllers\FeatureController::class, 'fpindex'])->name('feature.product');
        Route::get('featureproductCreate', [App\Http\Controllers\FeatureController::class, 'fpcreate'])->name('feature.product.create');
        Route::post('featureproductCreate', [App\Http\Controllers\FeatureController::class, 'fpstore'])->name('feature.product.store');
        Route::get('featureproEdit/{id}', [App\Http\Controllers\FeatureController::class, 'fpedit'])->name('feature.product.edit');
        Route::post('featureproEdit/{id}', [App\Http\Controllers\FeatureController::class, 'fpupdate'])->name('feature.product.update');
        Route::get('featureproList/{id}', [App\Http\Controllers\FeatureController::class, 'fpdestroy'])->name('feature.product.destroy');
    });

    Route::middleware(['auth', 'access:frontend-dynamics'])->prefix('admin')->name('')->group(function () {
//    Homepage Routes
        Route::resource('why-us', \App\Http\Controllers\WhyUsController::class);
        Route::resource('why-different', \App\Http\Controllers\WhyDifferentController::class);
        Route::resource('blogs', \App\Http\Controllers\BlogController::class);
        Route::resource('blogcates', \App\Http\Controllers\BlogcateController::class);
        Route::delete('blogcates/{id}', [\App\Http\Controllers\BlogcateController::class, 'destroy'])->name('blogcates.delete');
        Route::resource('testimonial', \App\Http\Controllers\TestimonialController::class);
        Route::post('testimonial/status/{id}', [\App\Http\Controllers\TestimonialController::class, 'statusChange'])->name('testimonial.change.status');
        Route::resource('association', \App\Http\Controllers\AssociationController::class);
        Route::post('association/status/{id}', [\App\Http\Controllers\AssociationController::class, 'statusChange'])->name('association.change.status');
//  About Us Routes
        Route::resource('about-us', \App\Http\Controllers\AboutUsController::class);
        Route::resource('values', \App\Http\Controllers\ValuesController::class);
        Route::resource('team', \App\Http\Controllers\TeamController::class);
        Route::get('team/status/{id}', [\App\Http\Controllers\TeamController::class, 'statusChange'])->name('team.change.status');
        Route::post('team/sort', [\App\Http\Controllers\TeamController::class, 'sort'])->name('team.sort');

//    Contact Us Routes
        Route::get('messages', [\App\Http\Controllers\MessagesController::class, 'index'])->name('message.index');
        Route::get('messages/show/{id}', [\App\Http\Controllers\MessagesController::class, 'show'])->name('message.show');
        Route::post('messages/update/{id}', [\App\Http\Controllers\MessagesController::class, 'update'])->name('message.update');
        Route::delete('messages/delete/{id}', [\App\Http\Controllers\MessagesController::class, 'delete'])->name('message.delete');
        Route::get('general-setting/contact', [\App\Http\Controllers\GeneralSettingController::class, 'contactList'])->name('general-setting.contact');
        Route::get('general-setting/contact/create', [\App\Http\Controllers\GeneralSettingController::class, 'contactCreate'])->name('general-setting.contact.create');
        Route::get('general-setting/contact/edit/{id}', [\App\Http\Controllers\GeneralSettingController::class, 'contactEdit'])->name('general-setting.contact.edit');
//    social Media Link Routes
        Route::resource('social-link', \App\Http\Controllers\SocialLinkController::class);
        Route::post('social/status/{id}', [\App\Http\Controllers\SocialLinkController::class, 'changeStatus'])->name('social.status');
        //user settings routes
        Route::resource('page-setting', \App\Http\Controllers\UserSettingController::class);

    });

    Route::middleware(['auth', 'access:page-seo-settings'])->prefix('admin')->name('')->group(function () {
//        Meta Data Routes
        Route::resource('meta', \App\Http\Controllers\MetaDataController::class);
        Route::post('meta/status/{id}', [App\Http\Controllers\MetaDataController::class, 'changeStatus'])->name('meta.status');

    });

    Route::middleware(['auth', 'access:general-settings'])->prefix('admin')->name('')->group(function () {
        Route::resource('general-setting', \App\Http\Controllers\GeneralSettingController::class);
        Route::resource('sms', \App\Http\Controllers\SmsResponseController::class);
    });

    Route::get('/admin/privilege/permission_roles/getpermission_rolesJson', [App\Http\Controllers\PermissionRoleController::class, 'getpermission_rolesJson'])->name('permission_roles.getdatajson');
    Route::middleware('access:create-user')->prefix('admin/privilege')->name('admin.privilege.')->group(function () {
        Route::resource('permission', \App\Http\Controllers\PermissionController::class);
        Route::resource('permission_roles', \App\Http\Controllers\PermissionRoleController::class);
        Route::resource('role', \App\Http\Controllers\RoleController::class);
        Route::resource('user', \App\Http\Controllers\UserController::class);
        Route::put('user/change/status/{user}', ['as' => 'user.change.status', 'uses' => '\App\Http\Controllers\UserController@changeStatus']);
        Route::get('/login/user/{id}', [\App\Http\Controllers\UserController::class, 'manuallogin'])->name('login.as.user');
        Route::get('/user/list/excel', [\App\Http\Controllers\UserController::class, 'downloadExcel'])->name('user.excel');
        Route::get('/user/companies/{id}', [\App\Http\Controllers\UserController::class, 'showCompanies'])->name('user.companies');
        Route::post('/user/companies/{id}', [\App\Http\Controllers\UserController::class, 'storeCompanies'])->name('user.companies.store');
    });

    Route::group(['middleware' => 'auth'], function () {
        Route::get('/dashboard', [\App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
        Route::post('filter/revenue', [App\Http\Controllers\DashboardController::class, 'filterRevenue'])->name('filter.revenue');
        Route::post('follow.update', [\App\Http\Controllers\DashboardController::class, 'followUpdate'])->name('follow.update');
        Route::get('/recentlyaddCustomer', [App\Http\Controllers\DashboardController::class, 'getrecentlyCustomer'])->name('getrecentlyaddCustomer');
        Route::get('/followupList', [App\Http\Controllers\DashboardController::class, 'getfollowupList'])->name('getfollowupList');
        Route::get('/lifeLeadershipList', [App\Http\Controllers\DashboardController::class, 'getLifeLeadershipList'])->name('getLifeLeadershipList');
        Route::get('/nonlifeLeadershipList', [App\Http\Controllers\DashboardController::class, 'getNonlifeLeaderList'])->name('getNonlifeLeadershipList');
        Route::get('/customer-kyc/{id}', [\App\Http\Controllers\KYCController::class, 'customerKyc'])->name('customer.kyc');
    });

    Route::middleware(['access:non-life-calculator-settings', 'agent:NonLife', 'cors', 'api'])->prefix('motor/manufacture/company')->name('motor.manufacture.company.')->group(function () {
        //manufactures
        Route::get('manufactures', [App\Http\Controllers\MotorManufactureCompanyController::class, 'index'])->name('list');
        Route::post('manufacture/store', [App\Http\Controllers\MotorManufactureCompanyController::class, 'store'])->name('list.store');
        Route::post('manufacture/update', [App\Http\Controllers\MotorManufactureCompanyController::class, 'update'])->name('list.update');
        Route::post('manufacture/delete/{id}', [App\Http\Controllers\MotorManufactureCompanyController::class, 'destroy'])->name('list.delete');
        Route::get('manufacture/status/{id}', [App\Http\Controllers\MotorManufactureCompanyController::class, 'statusChange'])->name('list.status');

        //Models
        Route::get('models', [App\Http\Controllers\MotorManufactureCompanyModelController::class, 'index'])->name('models');
        Route::post('model/excel/upload', [App\Http\Controllers\MotorManufactureCompanyModelController::class, 'uploadExcel'])->name('model.upload.excel');
        Route::post('model/delete/{id}', [App\Http\Controllers\MotorManufactureCompanyModelController::class, 'destroy'])->name('model.delete');
        Route::get('model/status/{id}', [App\Http\Controllers\MotorManufactureCompanyModelController::class, 'statusChange'])->name('model.status');
    });

resources/views/Backend/AboutUs/add.blade.php
@section('header_css')
    <link rel="stylesheet" href="{{asset('backend/css/external.css')}}">
@endsection
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
    name="about-us">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Add About Us Content</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{route('about-us.store')}}" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <div class="form-group">
                        <p><label for="file" name="loadimage">Upload Image</label></p>
                        <p><input type="file" class="form-control" accept="image/*" name="image" id="file"
                                  onchange="loadFile(event)" required></p>
                        <p><img id="output" width="200"/></p>
                        <p class="help-block">File Must Be In '.png' Image Format. Insert Image of 3 X 2</p>
                    </div>
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" value="{{old('title')}}" name="title" class="form-control"
                               placeholder="Enter Title">
                    </div>
                    <div class="form-group">
                        <label for="description">Comment</label>
                        <textarea name="description" value="{{old('description')}}" class="form-control" cols="5" rows="10"></textarea>
                    </div>
                    <div class="btnsubmit">
                        <br>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
@section('footer_js')
    <script>
        var loadFile = function (event) {
            var image = document.getElementById('output');
            image.src = URL.createObjectURL(event.target.files[0]);
        };
    </script>
@endsection

resources/views/Backend/AboutUs/edit.blade.php
@section('header_css')
    <link rel="stylesheet" href="{{asset('frontend/css/font-awesome.min.css')}}">
    <style>
        .img-responsive{
            max-width: 100%;
        }
        .gallery-img{
            height: 150px;
            width: 150px;
        }
        .btnsubmit{
            clear:both;
        }
    </style>
@endsection
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4>Edit About Us Content</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        </div>
        <div class="modal-body">
            <form method="POST" action="{{route('about-us.update',$why['id'])}}"
                  enctype="multipart/form-data">
                {{method_field('patch')}}
                {{csrf_field()}}
                <div class="form-group">
                    <label for="exampleInputFile">Select Image</label>
                    <input type="file" class="form-control" name="image" accept="image/*" id="exampleInputFile">
                    <p class="help-block">File Must Be In '.png' Image Format. Insert Image of 3 X 3</p>
                    <div class="gallery-img">
                        <a target="_blank" href="{{$why['image']}}"
                           class="swipebox" title="Image Title">
                            <img class="img-responsive"
                                 src="{{$why['image']}}" alt="">
                            <span class="zoom-icon"> </span> </a>
                    </div>
                </div>
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" value="{{$why['title']}}" class="form-control" id="title"
                           placeholder="Enter Title">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea name="description" class="form-control" id="description" cols="5"
                              rows="10">{{$why['description']}}</textarea>
                </div>
                <div class="btnsubmit">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

resources/views/Backend/AboutUs/index.blade.php
@extends('layouts.backend.containerlist')

@section('title')
    About Us Contents
@endsection
<style>
    .btnsubmit {
        clear: both;
    }

    .modal fade {
        display: none;
    }
</style>
@section('dynamicdata')

    <div class="box">
        <div class="box-header with-border c-btn-right d-flex-row ">
            <div class="justify-content-end list-group list-group-horizontal ">
            </div>
        </div>
        <div class="box-body">

            @include('layouts.backend.alert')
            <div id="accordion">
                <div class="card">
                    <div class="card-header" data-toggle="collapse" data-target="#collapseWhyDiff" aria-expanded="true"
                         aria-controls="collapseWhyDiff" id="WhyDiff">
                        <h5 class="mb-0 text-capitalize btn-link">
                            Click here to change Top side Contents <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                        </h5>
                    </div>

                    <div id="collapseWhyDiff" class="collapse" aria-labelledby="WhyDiff" data-parent="#accordion">
                        <div class="card-body">
                            <form class="p-2" method="POST" action="{{route('about-us.update',1)}}"
                                  enctype="multipart/form-data">
                                {{method_field('patch')}}
                                {{csrf_field()}}
                                <div class="form-group">
                                    <label for="title">Left Title</label>
                                    <input type="text" name="about_us_title"
                                           value="{{$aboutContent['about_us_title'] ? $aboutContent['about_us_title'] : ''}}"
                                           class="form-control" placeholder="Enter why us title">
                                </div>
                                <div class="form-group">
                                    <label for="why_us_content">Left Description</label>
                                    <textarea name="about_us_content" class="form-control" id="ckeditor" cols="5"
                                              rows="10">{{$aboutContent['about_us_content'] ? $aboutContent['about_us_content'] : ''}}</textarea>
                                </div>
                                <div class="btnsubmit">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            @if(count($about)< 3)
                <div class="justify-content-end list-group list-group-horizontal ">
                    <button type="button" class="btn btn-primary" data-toggle="modal"
                            data-target="#addModal">
                        Add
                    </button>
                    @include('Backend.AboutUs.add')
                </div>
            @endif
            <br>
            <div class="blank-page">
                <table class="table" id="datatable">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Image</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Actions</th>
                    </tr>
                    </thead>
                    <tbody id="tablebody">
                    @foreach($about as $why)
                        <tr>

                            <th scope="row">{{$loop->iteration}}</th>
                            <td>
                                <div class="col-md">
                                    <div class="gallery-img">
                                        <a target="_blank" href="{{$why['image']}}"
                                           class="swipebox" title="Image Title">
                                            <img class="img-responsive"
                                                 src="{{$why['image']}}" alt="">
                                            <span class="zoom-icon"> </span> </a>

                                    </div>
                                </div>
                            </td>
                            <td>
                                {{$why['title']}}
                            </td>
                            <td>{{$why['description']}}</td>
                            <td>
                                <button data-toggle="modal" data-target="#editModal{{$why['id']}}"
                                        class="btn btn-primary btn-flat mb-2">
                                    <i class="fa fa-edit"></i>
                                </button>
                                <a href="javascript:;" title="Delete about" class="delete-about"
                                   id="{{ $why->id }}">
                                    <button type="button" class="btn btn-danger btn-flat mb-2"><i
                                            class="fa fa-trash"></i></button>
                                </a>
                            </td>
                            <div class="modal fade" id="editModal{{$why['id']}}" tabindex="-1" role="dialog"
                                 aria-labelledby="myModalLabel"
                                 aria-hidden="true">
                                @include('Backend.AboutUs.edit')
                            </div>

                        </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>

        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection
@section('footer_js')
    <script>
        $('#tablebody').on('click', '.delete-about', function (e) {
            e.preventDefault();
            $object = $(this);
            var id = $object.attr('id');
            new swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then(function (response) {
                if (response.isConfirmed == true) {
                    $.ajax({
                        type: "DELETE",
                        url: "{{ url('/admin/about-us') }}" + "/" + id,
                        data: {
                            '_token': $('meta[name="csrf-token"]').attr('content')
                        },
                        beforeSend: function () {
                            $('#preloader').show();
                        },
                        dataType: 'json',
                        success: function (response) {
                            $('#preloader').hide();
                            var nRow = $($object).parents('tr')[0];
                            new swal(
                                'Success',
                                response.message,
                                'success'
                            )
                            $object.parent().parent().remove()
                        },
                        error: function (e) {
                            $('#preloader').hide();
                            new swal('Oops...', 'Something went wrong!', 'error');
                        }
                    });
                }
            }).catch(swal.noop);
        });
    </script>
@endsection