routes/frontend.php
<?php

use App\Http\Controllers\Frontend\CompareController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Frontend Table Routes
|--------------------------------------------------------------------------
*/

//HomePage
Route::get('lang/set', [App\Http\Controllers\LocalizationController::class, 'languageChange'])->name('setLanguage');

Route::get('/', [App\Http\Controllers\FrontendController::class, 'home'])->name('frontend.home');
Route::get('/calculator', [App\Http\Controllers\FrontendController::class, 'calculatorScreen'])->name('home.calculator');
//age
Route::post('/benefit', [App\Http\Controllers\FrontendController::class, 'benefits'])->name('home.benefits');

Route::post('/compare', [App\Http\Controllers\FrontendController::class, 'compareScreen'])->name('home.compare');
Route::get('/about', [App\Http\Controllers\FrontendController::class, 'about'])->name('frontend.about');

Route::get('/confirmation/{age}/{term}/{sum}/{mop}/{product}', [App\Http\Controllers\FrontendController::class, 'confirm'])->name('front.confirmation');

Route::post('corporateStore',[App\Http\Controllers\FrontendController::class,'corporateStore'])->name('lead.corporate');

Route::post('/confirm', [App\Http\Controllers\CalculationController::class, 'selectedPlanCalculation'])->name('front.confirm');

Route::get('get/cat/featureList', [App\Http\Controllers\FrontendController::class, 'findcatFeature'])->name('admin.get.category.feature');

Route::post('/plan/selected', [App\Http\Controllers\PlanselectedController::class, 'store'])->name('plan.selected');

Route::post('/plan/status/change', [App\Http\Controllers\PlanselectedController::class, 'updateStatus'])->name('plan.status.change');

//Route::get('/compare/result/demo',[App\Http\Controllers\FrontendController::class,'compareResult'])->name('compare.result.demo');

Route::post('frontend/add/lead', [App\Http\Controllers\Frontend\CompareController::class, 'leadCreate'])->name('frontend.add.lead');

Route::get('term-condition',[App\Http\Controllers\FrontendController::class,'termcondition'])->name('frontend.termcondition');
Route::get('privacy-policy',[App\Http\Controllers\FrontendController::class,'privacyPolicy'])->name('frontend.privacyPolicy');

Route::get('all/blogs',[App\Http\Controllers\FrontendController::class,'blogs'])->name('frontend.blogs');
Route::get('blog/{slug}',[App\Http\Controllers\FrontendController::class,'blogView'])->name('frontend.blog.view');

//contact
Route::get('contact', [App\Http\Controllers\FrontendController::class, 'contact'])->name('contact');
Route::post('contact', [App\Http\Controllers\FrontendController::class, 'contactStore'])->name('contact.message');

/**
 * Non-life Insurance Calculation
 */
Route::prefix('Nonlifeinsurance/calculator')->group(function () {
    Route::get('bike', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'nonlifecalculationForm']) ->name('frontend.nonlife.insurance');
    Route::post('motor', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'calculationMotor'])->name('frontend.nonlife.insurance.bike.calculation');
    Route::get('motors', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'calculationMotorview'])->name('frontend.nonlife.insurance.bike.view');
    Route::get('nonlife/detail', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'nonlifedetail'])->name('fronted.nonlife.details');
    Route::get('payment-view', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'paymentview'])->name('fronted.nonlife.payment');
    Route::post('motor/detail', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'detailmotor'])->name('fronted.bike.details');
    Route::post('/choosecustomer', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'choosecustomer'])->name('bike.customer.choose');
    Route::post('compulsary-excess', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'compulsaryExcess'])->name('motor.first.party.compulsary.excess');
    Route::post('excess-damage', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'excessDamage'])->name('bike.excess.damage');
    Route::post('manufacture-model', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'getModel'])->name('motor.first.party.model.manufacture');
    Route::post('make-draft-policy', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'makeDraftPolicy'])->name('construct.draft.policy');
    Route::get('make-policy', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'makeOnlinePolicy'])->name('motor.construct.policy');
    Route::get('/privatecar', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'carCalculator'])->name('private.car.nonlifeinsurance');
    Route::get('commerical-car', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'commercialCarCalculator'])->name('commerical.car.calculator.nonlifeinsurance');
    Route::get('invoice-pdf', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'loadPdf'])->name('pdf.invoice');
    // After KYC
    Route::post('motor-payment', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'paymentBikeFirstParty'])->name('motor.first.party.payment');
    Route::post('compulsary-excess', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'compulsaryExcess'])->name('bike.first.party.compulsary.excess');
    Route::post('excess-damage', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'excessDamage'])->name('motor.excess.damage');
    Route::get('policy-done', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'policyDone'])->name('policy.done');
    // Route::get('policy-view', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'viewPolicy'])->name('policy.detail.view');
    Route::get('draft-policy-view', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'viewDraftPolicy'])->name('policy.draft.view');
    Route::get('successfull/imepay', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'imePaySuccess'])->name('successfull.imepay');
    Route::get('unsuccessfull/imepay', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'imePayCancel'])->name('canceled.imepay');
    // Route::post('category-type', [App\Http\Controllers\Fronted\NonLifeCalculatorController::class, 'getCatType'])->name('bike.category.type');
    Route::get('debit-note', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'getDebitNote'])->name('bike.get.debit.note');
});

/**
 * Compare Routes
 */
Route::prefix('compare')
    ->name('compare.')
    ->group(function () {
        Route::get('', [CompareController::class, 'showCompareForm'])->name('form');
//        Route::post('result', [CompareController::class, 'compare'])->name('result');
        Route::post('viewplan',[CompareController::class,'viewPlan'])->name('viewplan');
        Route::post('result', [\App\Http\Controllers\CalculationController::class, 'frontendCompare'])->name('result');
    });

routes/web.php
    Route::middleware(['auth', 'access:create-product'])->prefix('admin')->name('admin.')->group(function () {
        Route::get('productList', [App\Http\Controllers\ProductController::class, 'index'])->name('product.list');
        Route::get('productDeletedList', [App\Http\Controllers\ProductController::class, 'trashedProductsList'])->name('product.deleted');
        Route::get('productDeletedList/{id}', [App\Http\Controllers\ProductController::class, 'restoreProduct'])->name('product.restore');
        Route::get('productCreate', [App\Http\Controllers\ProductController::class, 'create'])->name('product.create');
        Route::post('productCreate', [App\Http\Controllers\ProductController::class, 'store'])->name('product.store');
        Route::get('productEdit/{id}', [App\Http\Controllers\ProductController::class, 'edit'])->name('product.edit');
        Route::post('productEdit/{id}', [App\Http\Controllers\ProductController::class, 'update'])->name('product.update');
        Route::delete('productDelete/{id}', [App\Http\Controllers\ProductController::class, 'destroy'])->name('product.destroy');
        Route::patch('product-update-status', [App\Http\Controllers\ProductController::class, 'updateProductStatus'])->name('product.status');

        //categories
        Route::get('category', [ProductCategoriesController::class, 'index'])->name('category');
        Route::get('category/create', [ProductCategoriesController::class, 'create'])->name('category.create');
        Route::post('category/store', [ProductCategoriesController::class, 'store'])->name('category.store');
        Route::get('category/edit/{id}', [ProductCategoriesController::class, 'edit'])->name('category.edit');
        Route::post('category/update/{id}', [ProductCategoriesController::class, 'update'])->name('category.update');
        Route::delete('category/delete/{id}', [ProductCategoriesController::class, 'delete'])->name('category.delete');
        Route::post('category/status/{id}', [ProductCategoriesController::class, 'changeStatus'])->name('category.status');

        //Upload product management pdf
        Route::get('uploadProductFile', [App\Http\Controllers\UploadProductPdfController::class, 'index'])->name('product.uploadFile');
        Route::post('uploadProductFile', [App\Http\Controllers\UploadProductPdfController::class, 'store'])->name('product.storeProductFile');
        
        Route::get('support/create',[App\Http\Controllers\UploadProductPdfController::class,'support'])->name('support.create');
        Route::get('support',[App\Http\Controllers\UploadProductPdfController::class,'form'])->name('support.index');
        Route::post('support/supply', [App\Http\Controllers\UploadProductPdfController::class, 'supply'])->name('support.supply');
        Route::get('support/edit/{id}', [App\Http\Controllers\UploadProductPdfController::class, 'replace'])->name('support.replace');
        Route::post('support/update/{id}', [App\Http\Controllers\UploadProductPdfController::class, 'modernize'])->name('support.modernize');
        Route::get('productFile/{productFileId}/download', [App\Http\Controllers\UploadProductPdfController::class, 'download'])->name('product.downloadProductFile');
        Route::delete('upload/ProductFile/{id}', [App\Http\Controllers\UploadProductPdfController::class, 'destroy'])->name('product.uploadFile.delete');

        //  Upload choosefile with mail
        Route::get('videoupload',[App\Http\Controllers\UploadChooseFileController::class,'index'])->name('videoupload.index');
        Route::get('videoupload/create',[App\Http\Controllers\UploadChooseFileController::class,'create'])->name('videoupload.create');
        Route::post('videoupload/store',[App\Http\Controllers\UploadChooseFileController::class,'store'])->name('videoupload.store');
        Route::get('videoupload/show/{id}', [App\Http\Controllers\UploadChooseFileController::class, 'view'])->name('support.show');
        Route::delete('video/{id}', [App\Http\Controllers\UploadChooseFileController::class, 'destroy'])->name('videoupload.delete');
        // Route::resource('videoupload', \App\Http\Controllers\UploadProductPdfController::class);

        //video
         Route::get('tape',[App\Http\Controllers\VideoController::class,'index'])->name('tape.index');
         Route::get('tape/create',[App\Http\Controllers\VideoController::class,'create'])->name('tape.create'); 
         Route::post('tape/store',[App\Http\Controllers\VideoController::class,'store'])->name('tape.store');
         Route::delete('tape/{id}', [App\Http\Controllers\VideoController::class, 'destroy'])->name('tape.delete');
         Route::get('tape/show/{id}', [App\Http\Controllers\VideoController::class, 'show'])->name('tape.show');
        Route::delete('tape/{id}', [App\Http\Controllers\VideoController::class, 'destroy'])->name('tape.delete');
        // Route::get('upload/create',[App\Http\Controllers\VideoController::class,'create'])->name('upload.create');
        // Route::post('upload/store',[App\Http\Controllers\VideoController::class,'store'])->name('upload.store');
        // Route::delete('video/{id}', [App\Http\Controllers\VideoController::class, 'destroy'])->name('upload.delete');

    });

    Route::middleware(['auth', 'access:create-company'])->prefix('admin')->name('admin.')->group(function () {
        Route::resource('companies', CompaniesController::class);
        Route::post('company-update-status/{id}', [App\Http\Controllers\CompaniesController::class, 'updateCompanyStatus'])->name('company.status');
        Route::get('productView/{id}', [App\Http\Controllers\CompaniesController::class, 'product'])->name('company.product');
        Route::get('company-details/{id}', [App\Http\Controllers\CompaniesController::class, 'companyDetails'])->name('company.details');
        Route::post('company-details/update/{id}', [App\Http\Controllers\CompaniesController::class, 'companyDetailsUpdate'])->name('company.details.update');
    });

    Route::middleware(['auth', 'access:life-calculator-inputs'])->prefix('admin')->name('admin.')->group(function () {
//    crc Rate Routes
        Route::resource('crcrate', \App\Http\Controllers\CrcRateController::class);
        Route::delete('crcrate/delete/{id}', [App\Http\Controllers\CrcRateController::class, 'destroy'])->name('crcrate.delete');
//    Discount on SA Routes
        Route::get('discountList', [App\Http\Controllers\SumAssuredController::class, 'index'])->name('discount.list');
        Route::get('discountCreate', [App\Http\Controllers\SumAssuredController::class, 'create'])->name('discount.create');
        Route::post('discountCreate', [App\Http\Controllers\SumAssuredController::class, 'store'])->name('discount.store');
        Route::get('discountEdit/{id}', [App\Http\Controllers\SumAssuredController::class, 'edit'])->name('discount.edit');
        Route::post('discountEdit/{id}', [App\Http\Controllers\SumAssuredController::class, 'update'])->name('discount.update');
        Route::delete('discountList/{id}', [App\Http\Controllers\SumAssuredController::class, 'destroy'])->name('discount.destroy');

//    Bonus Routes
        Route::get('bonusList', [App\Http\Controllers\BonusRateEPController::class, 'index'])->name('bonus.list');
        Route::get('bonusCreate', [App\Http\Controllers\BonusRateEPController::class, 'create'])->name('bonus.create');
        Route::post('bonusCreate', [App\Http\Controllers\BonusRateEPController::class, 'store'])->name('bonus.store');
        Route::get('bonusEdit/{id}', [App\Http\Controllers\BonusRateEPController::class, 'edit'])->name('bonus.edit');
        Route::post('bonusEdit/{id}', [App\Http\Controllers\BonusRateEPController::class, 'update'])->name('bonus.update');
        Route::delete('bonusList/delete/{id}', [App\Http\Controllers\BonusRateEPController::class, 'destroy'])->name('bonus.delete');
//    Mode of Payment Routes
        Route::resource('loadingcharges', LoadingChargeController::class);
        Route::delete('loadingcharges/delete/{id}', [LoadingChargeController::class, 'destroy']);
//    Payback Schedule Routes
        Route::get('paybackSchedule', [\App\Http\Controllers\PaybackScheduleController::class, 'index'])->name('payback.index');
        Route::get('paybackSchedule/create', [\App\Http\Controllers\PaybackScheduleController::class, 'create'])->name('payback.create');
        Route::post('paybackSchedule/create', [\App\Http\Controllers\PaybackScheduleController::class, 'store'])->name('payback.store');
        Route::get('paybackSchedule/edit/{id}', [\App\Http\Controllers\PaybackScheduleController::class, 'edit'])->name('payback.edit');
        Route::post('paybackSchedule/edit/{id}', [\App\Http\Controllers\PaybackScheduleController::class, 'update'])->name('payback.update');
        Route::get('paybackSchedule/delete/{id}', [\App\Http\Controllers\PaybackScheduleController::class, 'destroy'])->name('payback.delete');
        Route::delete('paybackSchedule/delete/{id}', [\App\Http\Controllers\PaybackScheduleController::class, 'destroy'])->name('payback.destroy');
//    Couples Age Difference Routes
        Route::resource('age-difference', \App\Http\Controllers\CoupleAgeDifferenceController::class);
//    Policy Paying Term Routes
        Route::resource('paying-term', \App\Http\Controllers\PayingTermController::class);
//  Api Key Routes
        Route::resource('api-key', \App\Http\Controllers\ApiKeyController::class);
        // Feature Routes
        Route::get('get/featureList', [App\Http\Controllers\LifeCalculatorController::class, 'findFeature'])->name('get.feature.list');

        Route::get('featureList', [App\Http\Controllers\FeatureController::class, 'index'])->name('feature.list');
        Route::get('featureList', [App\Http\Controllers\FeatureController::class, 'index'])->name('feature.list');
        Route::get('featureList', [App\Http\Controllers\FeatureController::class, 'index'])->name('feature.list');

app/Models/Video.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    use HasFactory;
    protected $guarded = [];
    // public function user()
    // {
    //     return $this->belongsTo(User::class, 'user_id', 'id');
    // }
    public static function videofollowup(){
        $todayDate=Carbon::create(date('Y-m-d'));
        $roleId=auth()->user()->role_id;
        if($roleId!= 1 && $roleId!=7){
          $query=$query->where('title',auth()->user()->id);
        }else if($roleId==7){
           $query=$query->where('title',1);
        }
        $query=$query->groupBy('file');
        return $query;

    }
}

resources/views/Backend/video/create.blade.php
@extends('layouts.backend.containerlist')

@section('dynamicdata')

<div class="box box-success">
    <div class="box-header">
        <h3 class="box-title">Video Upload</h3>
    </div>
    <div class="box-body">
        @include('layouts.backend.alert')
        <form class="px-3" action="{{ route('admin.tape.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="title">Tittle</label>
                <div class="form-input">
                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" id=""
                    value="" placeholder="Social Media Title"> 
            </div>
            </div>
            <div class="form-group">
                 <label>Choose Video</label>
                 <div class="form-input">
                 <input class="input-control" name="file" type="file" id="" data-validation="required">
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Send</button>
        </form>
    </div>
</div>
@stop

resources/views/Backend/video/index.blade.php
@extends('layouts.backend.containerlist')

@section('title')
  Video
@endsection

@section('footer_js')
    <script type="text/javascript">
         $(document).on('click','.add-video',function(){
        window.location = "{{ route('admin.tape.create')}}"
        });
        $('#tablebody').on('click', '.delete-tape', function (e) {
            e.preventDefault();
            $object = $(this);
            var id = $object.attr('id'); 
            new swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then(function (response) {
                if (response.isConfirmed == true) {
                    $.ajax({
                        type: "DELETE",
                        url: "tape/"+id,
                        data: {
                            '_token': $('meta[name="csrf-token"]').attr('content')
                        },
                        dataType: 'json',
                        beforeSend: function () {
                            $('#preloader').show();
                        },
                        success: function (response) {
                            $('#preloader').hide();
                            var nRow = $($object).parents('tr')[0];
                            new swal(
                                'Success',
                                response.message,
                                'success'
                            )
                            $object.parent().parent().remove()
                        },
                        error: function (e) {
                            $('#preloader').hide();
                            new swal('Oops...', 'Something went wrong!', 'error');
                        }
                    });
                }
            }).catch(swal.noop);
        });
    </script>
         {!! $dataTable->scripts() !!}
@endsection

@section('dynamicdata')

<div class="box">
    <div class="box-body">
        {!! $dataTable->table() !!}
    </div>
</div>
@endsection

resources/views/Backend/video/view.blade.php
@extends('layouts.backend.containerlist')

@section('dynamicdata')

<div class="box box-success">
    <div class="box-header">
        <h3 class="box-title">Video Upload</h3>
    </div>
    <div class="box-body">
        @include('layouts.backend.alert')
        <form class="px-3" action="{{ route('admin.tape.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="title">Tittle</label>
                <div class="form-input">
                <input type="text" class="form-control @error('title') is-invalid @enderror" 
                value="{{old('name', $supportvideo->title)}}" readonly> 
            </div>
            </div>
            <div class="form-group">
                 <label>Choose Video</label>
                 <div class="form-input">
                 <iframe src="/assets/{{ $supportvideo->file }}"></iframe>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Send</button>
        </form>
    </div>
</div>
@stop