routes/frontend.php
<?php

use App\Http\Controllers\Frontend\CompareController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Frontend Table Routes
|--------------------------------------------------------------------------
*/

//HomePage
Route::get('lang/set', [App\Http\Controllers\LocalizationController::class, 'languageChange'])->name('setLanguage');

Route::get('/', [App\Http\Controllers\FrontendController::class, 'home'])->name('frontend.home');
Route::get('/calculator', [App\Http\Controllers\FrontendController::class, 'calculatorScreen'])->name('home.calculator');
//age
Route::post('/benefit', [App\Http\Controllers\FrontendController::class, 'benefits'])->name('home.benefits');

Route::post('/compare', [App\Http\Controllers\FrontendController::class, 'compareScreen'])->name('home.compare');
Route::get('/about', [App\Http\Controllers\FrontendController::class, 'about'])->name('frontend.about');

Route::get('/confirmation/{age}/{term}/{sum}/{mop}/{product}', [App\Http\Controllers\FrontendController::class, 'confirm'])->name('front.confirmation');

Route::post('corporateStore',[App\Http\Controllers\FrontendController::class,'corporateStore'])->name('lead.corporate');

Route::post('/confirm', [App\Http\Controllers\CalculationController::class, 'selectedPlanCalculation'])->name('front.confirm');

Route::get('get/cat/featureList', [App\Http\Controllers\FrontendController::class, 'findcatFeature'])->name('admin.get.category.feature');

Route::post('/plan/selected', [App\Http\Controllers\PlanselectedController::class, 'store'])->name('plan.selected');

Route::post('/plan/status/change', [App\Http\Controllers\PlanselectedController::class, 'updateStatus'])->name('plan.status.change');

//Route::get('/compare/result/demo',[App\Http\Controllers\FrontendController::class,'compareResult'])->name('compare.result.demo');

Route::post('frontend/add/lead', [App\Http\Controllers\Frontend\CompareController::class, 'leadCreate'])->name('frontend.add.lead');

Route::get('term-condition',[App\Http\Controllers\FrontendController::class,'termcondition'])->name('frontend.termcondition');
Route::get('privacy-policy',[App\Http\Controllers\FrontendController::class,'privacyPolicy'])->name('frontend.privacyPolicy');

Route::get('all/blogs',[App\Http\Controllers\FrontendController::class,'blogs'])->name('frontend.blogs');
Route::get('blog/{slug}',[App\Http\Controllers\FrontendController::class,'blogView'])->name('frontend.blog.view');

//contact
Route::get('contact', [App\Http\Controllers\FrontendController::class, 'contact'])->name('contact');
Route::post('contact', [App\Http\Controllers\FrontendController::class, 'contactStore'])->name('contact.message');

/**
 * Non-life Insurance Calculation
 */
Route::prefix('Nonlifeinsurance/calculator')->group(function () {
    Route::get('bike', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'nonlifecalculationForm']) ->name('frontend.nonlife.insurance');
    Route::post('motor', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'calculationMotor'])->name('frontend.nonlife.insurance.bike.calculation');
    Route::get('motors', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'calculationMotorview'])->name('frontend.nonlife.insurance.bike.view');
    Route::get('nonlife/detail', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'nonlifedetail'])->name('fronted.nonlife.details');
    Route::get('payment-view', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'paymentview'])->name('fronted.nonlife.payment');
    Route::post('motor/detail', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'detailmotor'])->name('fronted.bike.details');
    Route::post('/choosecustomer', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'choosecustomer'])->name('bike.customer.choose');
    Route::post('compulsary-excess', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'compulsaryExcess'])->name('motor.first.party.compulsary.excess');
    Route::post('excess-damage', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'excessDamage'])->name('bike.excess.damage');
    Route::post('manufacture-model', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'getModel'])->name('motor.first.party.model.manufacture');
    Route::post('make-draft-policy', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'makeDraftPolicy'])->name('construct.draft.policy');
    Route::get('make-policy', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'makeOnlinePolicy'])->name('motor.construct.policy');
    Route::get('/privatecar', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'carCalculator'])->name('private.car.nonlifeinsurance');
    Route::get('commerical-car', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'commercialCarCalculator'])->name('commerical.car.calculator.nonlifeinsurance');
    Route::get('invoice-pdf', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'loadPdf'])->name('pdf.invoice');
    // After KYC
    Route::post('motor-payment', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'paymentBikeFirstParty'])->name('motor.first.party.payment');
    Route::post('compulsary-excess', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'compulsaryExcess'])->name('bike.first.party.compulsary.excess');
    Route::post('excess-damage', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'excessDamage'])->name('motor.excess.damage');
    Route::get('policy-done', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'policyDone'])->name('policy.done');
    // Route::get('policy-view', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'viewPolicy'])->name('policy.detail.view');
    Route::get('draft-policy-view', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'viewDraftPolicy'])->name('policy.draft.view');
    Route::get('successfull/imepay', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'imePaySuccess'])->name('successfull.imepay');
    Route::get('unsuccessfull/imepay', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'imePayCancel'])->name('canceled.imepay');
    // Route::post('category-type', [App\Http\Controllers\Fronted\NonLifeCalculatorController::class, 'getCatType'])->name('bike.category.type');
    Route::get('debit-note', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'getDebitNote'])->name('bike.get.debit.note');
});

/**
 * Compare Routes
 */
Route::prefix('compare')
    ->name('compare.')
    ->group(function () {
        Route::get('', [CompareController::class, 'showCompareForm'])->name('form');
//        Route::post('result', [CompareController::class, 'compare'])->name('result');
        Route::post('viewplan',[CompareController::class,'viewPlan'])->name('viewplan');
        Route::post('result', [\App\Http\Controllers\CalculationController::class, 'frontendCompare'])->name('result');
    });

routes/web.php
    Route::middleware(['auth', 'access:create-leads'])->prefix('admin')->name('admin.')->group(function () {
        Route::resource('leads', \App\Http\Controllers\LeadController::class);
        Route::get('get-form-convert-to-policy', [App\Http\Controllers\LeadController::class, 'getFormConvertToPolicy'])->name('leads.getformConvertToPolicy');
        Route::post('getspecificLead', [App\Http\Controllers\LeadController::class, 'getspecificLead'])->name('leads.getspecificLead');
        Route::post('lead/add/remark', [App\Http\Controllers\LeadController::class, 'addRemarkLead'])->name('leads.Addremark');
        Route::post('lead/getProduct', [App\Http\Controllers\LeadController::class, 'getProduct'])->name('leads.getProduct');

        Route::post('lead/findUser', [App\Http\Controllers\LeadController::class, 'findUser'])->name('leads.findUser');
        Route::post('lead/document', [App\Http\Controllers\LeadController::class, 'leadDocument'])->name('leads.document');
        Route::get('customers', [App\Http\Controllers\LeadController::class, 'customersList'])->name('leads.customers');
        Route::post('leads/document/delete', [App\Http\Controllers\LeadController::class, 'documentDelete'])->name('leads.documentDelete');
        Route::post('lead/getCity', [App\Http\Controllers\LeadController::class, 'getCity'])->name('leads.getCity');
        Route::get('getCityList/{id}', [App\Http\Controllers\LeadController::class, 'getCityList']);
        Route::post('leads/create/client', [App\Http\Controllers\LeadController::class, 'makeUser'])->name('lead.make.user');
        Route::post('leads/update', [App\Http\Controllers\LeadController::class, 'update'])->name('lead.update');
        Route::get('leads/delete/{id}', [App\Http\Controllers\LeadController::class, 'delete'])->name('leads.delete');

        Route::get('lead/getleadremarks/{id}', [App\Http\Controllers\LeadController::class, 'GetRemarkList'])->name('leads.remarklist');
        Route::post('lead/remarks/', [App\Http\Controllers\LeadController::class, 'remark'])->name('leads.remarks');
        Route::post('lead/meetings/', [App\Http\Controllers\LeadController::class, 'meeting'])->name('leads.meetings');
        Route::get('lead/getleadmeetings/{id}', [App\Http\Controllers\LeadController::class, 'GetMeetingList'])->name('leads.meetinglist');

        Route::get('lead/demo-export', [\App\Http\Controllers\LeadController::class, 'export'])->name('leads.exportDemo');
        Route::post('lead/import', [\App\Http\Controllers\LeadController::class, 'importFile'])->name('leads.import');

        Route::post('premiumPaidByCustomer', [App\Http\Controllers\LeadController::class, 'updatePremiumPaidByCustomer'])->name('leads.updatePremiumPaidByCustomer');
        Route::post('customer-verify', [App\Http\Controllers\LeadController::class, 'customerVerify'])->name('customerVerify');
        Route::get('premium-paid-by-customer', [App\Http\Controllers\PremiumPaidController::class, 'index'])->name('permiumpaid');
        Route::post('get-premium-collection-user', [App\Http\Controllers\PremiumPaidController::class, 'getPremiumCollection'])->name('getPremiumCollection');
        Route::post('premium-verify', [App\Http\Controllers\PremiumPaidController::class, 'premiumVerify'])->name('premiumVerify');
    });

    Route::prefix('admin')->name('admin.')->group(function () {
        Route::get('seo-form', [App\Http\Controllers\SeoFormController::class, 'index'])->name('seoForm');
        Route::get('seo-form-create', [App\Http\Controllers\SeoFormController::class, 'create'])->name('seoForm.create');
        Route::post('seo-form/create', [App\Http\Controllers\SeoFormController::class, 'store'])->name('seoForm.store');
        Route::get('seo-form/edit/{id}', [App\Http\Controllers\SeoFormController::class, 'edit'])->name('seoForm.edit');
        Route::post('seo-form/edit/{id}', [App\Http\Controllers\SeoFormController::class, 'update'])->name('seoForm.update');
        Route::delete('seo-form/delete', [App\Http\Controllers\SeoFormController::class, 'delete'])->name('seoForm.delete');
    });

    Route::middleware(['auth', 'access:create-policy'])->prefix('admin/policycategories')->name('admin.policycategories.')->group(function () {
        Route::resource('sub', \App\Http\Controllers\PolicySubCategoryController::class)->except('create', 'show');
        Route::resource('type', \App\Http\Controllers\PolicyTypeController::class)->except('create', 'show');
    });

    Route::middleware(['auth', 'access:create-product'])->prefix('admin')->name('admin.')->group(function () {
        Route::get('productList', [App\Http\Controllers\ProductController::class, 'index'])->name('product.list');
        Route::get('productDeletedList', [App\Http\Controllers\ProductController::class, 'trashedProductsList'])->name('product.deleted');
        Route::get('productDeletedList/{id}', [App\Http\Controllers\ProductController::class, 'restoreProduct'])->name('product.restore');
        Route::get('productCreate', [App\Http\Controllers\ProductController::class, 'create'])->name('product.create');
        Route::post('productCreate', [App\Http\Controllers\ProductController::class, 'store'])->name('product.store');
        Route::get('productEdit/{id}', [App\Http\Controllers\ProductController::class, 'edit'])->name('product.edit');
        Route::post('productEdit/{id}', [App\Http\Controllers\ProductController::class, 'update'])->name('product.update');
        Route::delete('productDelete/{id}', [App\Http\Controllers\ProductController::class, 'destroy'])->name('product.destroy');
        Route::patch('product-update-status', [App\Http\Controllers\ProductController::class, 'updateProductStatus'])->name('product.status');

        //categories
        Route::get('category', [ProductCategoriesController::class, 'index'])->name('category');
        Route::get('category/create', [ProductCategoriesController::class, 'create'])->name('category.create');
        Route::post('category/store', [ProductCategoriesController::class, 'store'])->name('category.store');
        Route::get('category/edit/{id}', [ProductCategoriesController::class, 'edit'])->name('category.edit');
        Route::post('category/update/{id}', [ProductCategoriesController::class, 'update'])->name('category.update');
        Route::delete('category/delete/{id}', [ProductCategoriesController::class, 'delete'])->name('category.delete');
        Route::post('category/status/{id}', [ProductCategoriesController::class, 'changeStatus'])->name('category.status');

        //Upload product management pdf
        Route::get('uploadProductFile', [App\Http\Controllers\UploadProductPdfController::class, 'index'])->name('product.uploadFile');
        Route::post('uploadProductFile', [App\Http\Controllers\UploadProductPdfController::class, 'store'])->name('product.storeProductFile');
        
        Route::get('support/create',[App\Http\Controllers\UploadProductPdfController::class,'support'])->name('support.create');
        Route::get('support',[App\Http\Controllers\UploadProductPdfController::class,'form'])->name('support.index');
        Route::post('support/supply', [App\Http\Controllers\UploadProductPdfController::class, 'supply'])->name('support.supply');
        Route::get('support/edit/{id}', [App\Http\Controllers\UploadProductPdfController::class, 'replace'])->name('support.replace');
        Route::post('support/update/{id}', [App\Http\Controllers\UploadProductPdfController::class, 'modernize'])->name('support.modernize');
        Route::get('productFile/{productFileId}/download', [App\Http\Controllers\UploadProductPdfController::class, 'download'])->name('product.downloadProductFile');
        Route::delete('upload/ProductFile/{id}', [App\Http\Controllers\UploadProductPdfController::class, 'destroy'])->name('product.uploadFile.delete');

        //  Upload choosefile with mail
        Route::get('videoupload',[App\Http\Controllers\UploadChooseFileController::class,'index'])->name('videoupload.index');
        Route::get('videoupload/create',[App\Http\Controllers\UploadChooseFileController::class,'create'])->name('videoupload.create');
        Route::post('videoupload/store',[App\Http\Controllers\UploadChooseFileController::class,'store'])->name('videoupload.store');
        Route::get('videoupload/show/{id}', [App\Http\Controllers\UploadChooseFileController::class, 'view'])->name('support.show');
        Route::delete('video/{id}', [App\Http\Controllers\UploadChooseFileController::class, 'destroy'])->name('videoupload.delete');
        // Route::resource('videoupload', \App\Http\Controllers\UploadProductPdfController::class);

        //video
         Route::get('tape',[App\Http\Controllers\VideoController::class,'index'])->name('tape.index');
         Route::get('tape/create',[App\Http\Controllers\VideoController::class,'create'])->name('tape.create'); 
         Route::post('tape/store',[App\Http\Controllers\VideoController::class,'store'])->name('tape.store');
         Route::delete('tape/{id}', [App\Http\Controllers\VideoController::class, 'destroy'])->name('tape.delete');
         Route::get('tape/show/{id}', [App\Http\Controllers\VideoController::class, 'show'])->name('tape.show');
        Route::delete('tape/{id}', [App\Http\Controllers\VideoController::class, 'destroy'])->name('tape.delete');
        // Route::get('upload/create',[App\Http\Controllers\VideoController::class,'create'])->name('upload.create');
        // Route::post('upload/store',[App\Http\Controllers\VideoController::class,'store'])->name('upload.store');
        // Route::delete('video/{id}', [App\Http\Controllers\VideoController::class, 'destroy'])->name('upload.delete');

    });

    Route::middleware(['auth', 'access:create-company'])->prefix('admin')->name('admin.')->group(function () {
        Route::resource('companies', CompaniesController::class);

resources/views/Backend/seoform/form.blade.php
@extends('layouts.backend.containerlist')
@section('title')
    {{isset($seoform) ? 'Edit' : 'Create' }} Seo Form
@endsection
@section('footer_js')
@endsection
@php
    $url=isset($seoform) ? route('admin.seoForm.edit',['id'=>$seoform->id]) : route('admin.seoForm.store');
@endphp
@section('dynamicdata')
    <div class="box">
        <div class="box-body">
            <div class="policy-compare-wrapper">
                <div class="form-wrapper">
                    <form class="form-data" method="POST" action="{{ $url }}" >
                        @csrf
                        <div class="custom-row">
                            <div class="form-input-wrapper">
                                <div class="form-label">
                                    <label>Form Name<label>
                                </div>
                                <div class="form-input">
                                    <input type="text" name="form_name" class="input-control"  value="{{isset($seoform) ? $seoform->form_name : old('form_name')}}">
                                    @if ($errors->has('form_name'))
                                        <p class="validation-error"><i class="fa fa-times-circle"></i>&nbsp;{{ $errors->first('form_name') }}</p>
                                    @endif
                                </div>
                            </div>
                             <div class="form-input-wrapper">
                                <div class="form-label">
                                    <label>Form Id<label>
                                </div>
                                <div class="form-input">
                                    <input type="text" name="form_id" class="input-control" value="{{isset($seoform) ? $seoform->form_id : old('form_id')}}">
                                    @if ($errors->has('form_id'))
                                        <p class="validation-error"><i class="fa fa-times-circle"></i>&nbsp;{{ $errors->first('form_id') }}</p>
                                    @endif
                                </div>
                            </div>
                            <div class="form-input-wrapper">
                                    <div class="form-label"></div>
                                <div class="form-input">
                                    <button type="submit" id="submit-btn" class="form-submit-btn">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Backend/seoform/index.blade.php
@extends('layouts.backend.containerlist')
@section('title')
    Seo Form
@endsection
@section('footer_js')
        <script type="text/javascript">
            @if(\Session::has('message'))
                new swal('success','{{\Session::get('message')}}','success')
            @endif
        </script>
    
    {!! $dataTable->scripts() !!}
    @include('Backend.seoform.seoform-script')
@endsection


@section('dynamicdata')
    <div class="box">
        <div class="box-body">
           {!! $dataTable->table() !!}
        </div>
    </div>
@endsection

resources/views/Backend/seoform/seoform-script.blade.php
<script>
	this.seoFormIntial=function(){
		let _this=this
		this.deleteSeoFormListener=function(){
			$(document).on('click','.delete-seo-form',function(){
				let id =$(this).data('id')
				 $object = $(this);
				new swal({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                }).then(function (response) {
                    if(response.isConfirmed == true){
                        $.ajax({
                            type: "DELETE",
                            url: "{{ route('admin.seoForm.delete') }}",
                            data:{
                            	id:id,
                                '_token': $('meta[name="csrf-token"]').attr('content')
                            },
                            beforeSend: function () {
                                $('#preloader').show();
                            },

                            dataType: 'json',
                            success: function (response) {
                                $('#preloader').hide();
                                var nRow = $($object).parents('tr')[0];
                                new swal(
                                    'Success',
                                    response.message,
                                    'success'
                                )
                                  $object.parent().parent().remove()
                            },
                            error: function (e) {
                                $('#preloader').hide();
                                new swal('Oops...', 'Something went wrong!', 'error');
                            }
                        });
                    }


                }).catch(swal.noop);
			})
		},
		this.init=function(){
			_this.deleteSeoFormListener()
		}
	}
	let seoFormObj=new seoFormIntial()
		seoFormObj.init()
</script>