routes/frontend.php
<?php

use App\Http\Controllers\Frontend\CompareController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Frontend Table Routes
|--------------------------------------------------------------------------
*/

//HomePage
Route::get('lang/set', [App\Http\Controllers\LocalizationController::class, 'languageChange'])->name('setLanguage');

Route::get('/', [App\Http\Controllers\FrontendController::class, 'home'])->name('frontend.home');
Route::get('/calculator', [App\Http\Controllers\FrontendController::class, 'calculatorScreen'])->name('home.calculator');
//age
Route::post('/benefit', [App\Http\Controllers\FrontendController::class, 'benefits'])->name('home.benefits');

Route::post('/compare', [App\Http\Controllers\FrontendController::class, 'compareScreen'])->name('home.compare');
Route::get('/about', [App\Http\Controllers\FrontendController::class, 'about'])->name('frontend.about');

Route::get('/confirmation/{age}/{term}/{sum}/{mop}/{product}', [App\Http\Controllers\FrontendController::class, 'confirm'])->name('front.confirmation');

Route::post('corporateStore',[App\Http\Controllers\FrontendController::class,'corporateStore'])->name('lead.corporate');

Route::post('/confirm', [App\Http\Controllers\CalculationController::class, 'selectedPlanCalculation'])->name('front.confirm');

Route::get('get/cat/featureList', [App\Http\Controllers\FrontendController::class, 'findcatFeature'])->name('admin.get.category.feature');

Route::post('/plan/selected', [App\Http\Controllers\PlanselectedController::class, 'store'])->name('plan.selected');

Route::post('/plan/status/change', [App\Http\Controllers\PlanselectedController::class, 'updateStatus'])->name('plan.status.change');

//Route::get('/compare/result/demo',[App\Http\Controllers\FrontendController::class,'compareResult'])->name('compare.result.demo');

Route::post('frontend/add/lead', [App\Http\Controllers\Frontend\CompareController::class, 'leadCreate'])->name('frontend.add.lead');

Route::get('term-condition',[App\Http\Controllers\FrontendController::class,'termcondition'])->name('frontend.termcondition');
Route::get('privacy-policy',[App\Http\Controllers\FrontendController::class,'privacyPolicy'])->name('frontend.privacyPolicy');

Route::get('all/blogs',[App\Http\Controllers\FrontendController::class,'blogs'])->name('frontend.blogs');
Route::get('blog/{slug}',[App\Http\Controllers\FrontendController::class,'blogView'])->name('frontend.blog.view');

//contact
Route::get('contact', [App\Http\Controllers\FrontendController::class, 'contact'])->name('contact');
Route::post('contact', [App\Http\Controllers\FrontendController::class, 'contactStore'])->name('contact.message');

/**
 * Non-life Insurance Calculation
 */
Route::prefix('Nonlifeinsurance/calculator')->group(function () {
    Route::get('bike', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'nonlifecalculationForm']) ->name('frontend.nonlife.insurance');
    Route::post('motor', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'calculationMotor'])->name('frontend.nonlife.insurance.bike.calculation');
    Route::get('motors', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'calculationMotorview'])->name('frontend.nonlife.insurance.bike.view');
    Route::get('nonlife/detail', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'nonlifedetail'])->name('fronted.nonlife.details');
    Route::get('payment-view', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'paymentview'])->name('fronted.nonlife.payment');
    Route::post('motor/detail', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'detailmotor'])->name('fronted.bike.details');
    Route::post('/choosecustomer', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'choosecustomer'])->name('bike.customer.choose');
    Route::post('compulsary-excess', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'compulsaryExcess'])->name('motor.first.party.compulsary.excess');
    Route::post('excess-damage', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'excessDamage'])->name('bike.excess.damage');
    Route::post('manufacture-model', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'getModel'])->name('motor.first.party.model.manufacture');
    Route::post('make-draft-policy', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'makeDraftPolicy'])->name('construct.draft.policy');
    Route::get('make-policy', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'makeOnlinePolicy'])->name('motor.construct.policy');
    Route::get('/privatecar', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'carCalculator'])->name('private.car.nonlifeinsurance');
    Route::get('commerical-car', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'commercialCarCalculator'])->name('commerical.car.calculator.nonlifeinsurance');
    Route::get('invoice-pdf', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'loadPdf'])->name('pdf.invoice');
    // After KYC
    Route::post('motor-payment', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'paymentBikeFirstParty'])->name('motor.first.party.payment');
    Route::post('compulsary-excess', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'compulsaryExcess'])->name('bike.first.party.compulsary.excess');
    Route::post('excess-damage', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'excessDamage'])->name('motor.excess.damage');
    Route::get('policy-done', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'policyDone'])->name('policy.done');
    // Route::get('policy-view', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'viewPolicy'])->name('policy.detail.view');
    Route::get('draft-policy-view', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'viewDraftPolicy'])->name('policy.draft.view');
    Route::get('successfull/imepay', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'imePaySuccess'])->name('successfull.imepay');
    Route::get('unsuccessfull/imepay', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'imePayCancel'])->name('canceled.imepay');
    // Route::post('category-type', [App\Http\Controllers\Fronted\NonLifeCalculatorController::class, 'getCatType'])->name('bike.category.type');
    Route::get('debit-note', [App\Http\Controllers\Frontend\NonLifeCalculatorController::class, 'getDebitNote'])->name('bike.get.debit.note');
});

/**
 * Compare Routes
 */
Route::prefix('compare')
    ->name('compare.')
    ->group(function () {
        Route::get('', [CompareController::class, 'showCompareForm'])->name('form');
//        Route::post('result', [CompareController::class, 'compare'])->name('result');
        Route::post('viewplan',[CompareController::class,'viewPlan'])->name('viewplan');
        Route::post('result', [\App\Http\Controllers\CalculationController::class, 'frontendCompare'])->name('result');
    });

routes/web.php
    Route::get('/login', [App\Http\Controllers\Auth\LoginController::class, 'login'])->name('login.login');
    Route::post('/login', [App\Http\Controllers\Auth\LoginController::class, 'authenticate'])->name('auth.login');
    Route::post('logout', [App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');
    Route::get('register', [App\Http\Controllers\Auth\RegisterController::class, 'showRegistrationForm'])->name('register');
    Route::post('register', [App\Http\Controllers\Auth\RegisterController::class, 'adduser'])->name('user.register');
});
Route::middleware(['userlogs', 'subscription'])->group(function () {

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


    Route::middleware(['auth', 'access:create-leads'])->prefix('admin')->name('admin.')->group(function () {
        Route::get('full-calender', [App\Http\Controllers\FullCalenderController::class, 'index'])->name('calender.event');
        Route::get('full-calender-meeting', [App\Http\Controllers\FullCalenderController::class, 'meeting'])->name('calender.meeting');

        Route::post('full-calender/store', [App\Http\Controllers\FullCalenderController::class, 'action']);
        Route::post('full-calender-meeting/store', [App\Http\Controllers\FullCalenderController::class, 'actionmeet']);
    });

    Route::middleware(['auth', 'access:non-life-calculation'])->prefix('admin')->name('admin.')->group(function () {

        Route::get('life/rate/validate', [App\Http\Controllers\LifeCalculatorController::class, 'validateRate'])->name('life.rate.validate');

        Route::get('ime-life-insurance', [ImelifeController::class, 'imelife'])
            ->name('ime.life.insurance');
        Route::post('ime-life-insurance/one', [ImelifeController::class, 'postimeOne'])
            ->name('ime.life.insurance.one');
        Route::get('ime-life-insurance/choose', [ImelifeController::class, 'imelifetwo'])
            ->name('ime.life.two');
        Route::post('ime-life-insurance/two', [ImelifeController::class, 'postimeTwo'])
            ->name('ime.life.insurance.two');
        Route::get('ime-life-insurance/confirm', [ImelifeController::class, 'imelifethree'])
            ->name('ime.life.three');
        Route::post('ime-life-insurance/three', [ImelifeController::class, 'postimeThree'])
            ->name('ime.life.insurance.three');
        Route::get('ime-life-insurance/personal-info', [ImelifeController::class, 'imelifefour'])
            ->name('ime.life.four');
        Route::post('ime-life-insurance/four', [ImelifeController::class, 'postimefour'])
            ->name('ime.life.insurance.four');
        Route::get('ime-life-insurance/details-of-plan', [ImelifeController::class, 'imelifefive'])
            ->name('ime.life.five');
        Route::post('ime-life-insurance/final-confirmation', [ImelifeController::class, 'postimefive'])
            ->name('ime.life.insurance.five');
        Route::get('ime-life-insurance/final-details-of-plan', [ImelifeController::class, 'imelifesix'])
            ->name('ime.life.six');
    });

    Route::middleware(['auth', 'access:create-leads'])->prefix('admin/leadcategories')->name('admin.leadcategories.')->group(function () {
        Route::resource('leadsource', \App\Http\Controllers\LeadSourceController::class)->except('show');
        Route::resource('leadtypes', \App\Http\Controllers\LeadTypeController::class)->except('create', 'show');
    });
    Route::middleware(['auth', 'access:marketing-leads'])->prefix('admin')->name('admin.')->group(function () {
        Route::get('lead/marketing', [App\Http\Controllers\LeadController::class, 'marketingLead'])->name('leads.marketing');
    });
    Route::middleware(['auth', 'access:create-leads'])->prefix('admin')->name('admin.')->group(function () {
        Route::resource('leads', \App\Http\Controllers\LeadController::class);
        Route::get('get-form-convert-to-policy', [App\Http\Controllers\LeadController::class, 'getFormConvertToPolicy'])->name('leads.getformConvertToPolicy');
        Route::post('getspecificLead', [App\Http\Controllers\LeadController::class, 'getspecificLead'])->name('leads.getspecificLead');
        Route::post('lead/add/remark', [App\Http\Controllers\LeadController::class, 'addRemarkLead'])->name('leads.Addremark');
        Route::post('lead/getProduct', [App\Http\Controllers\LeadController::class, 'getProduct'])->name('leads.getProduct');

        Route::post('lead/findUser', [App\Http\Controllers\LeadController::class, 'findUser'])->name('leads.findUser');
        Route::post('lead/document', [App\Http\Controllers\LeadController::class, 'leadDocument'])->name('leads.document');
        Route::get('customers', [App\Http\Controllers\LeadController::class, 'customersList'])->name('leads.customers');
        Route::post('leads/document/delete', [App\Http\Controllers\LeadController::class, 'documentDelete'])->name('leads.documentDelete');
        Route::post('lead/getCity', [App\Http\Controllers\LeadController::class, 'getCity'])->name('leads.getCity');
        Route::get('getCityList/{id}', [App\Http\Controllers\LeadController::class, 'getCityList']);
        Route::post('leads/create/client', [App\Http\Controllers\LeadController::class, 'makeUser'])->name('lead.make.user');
        Route::post('leads/update', [App\Http\Controllers\LeadController::class, 'update'])->name('lead.update');
        Route::get('leads/delete/{id}', [App\Http\Controllers\LeadController::class, 'delete'])->name('leads.delete');

        Route::get('lead/getleadremarks/{id}', [App\Http\Controllers\LeadController::class, 'GetRemarkList'])->name('leads.remarklist');
        Route::post('lead/remarks/', [App\Http\Controllers\LeadController::class, 'remark'])->name('leads.remarks');
        Route::post('lead/meetings/', [App\Http\Controllers\LeadController::class, 'meeting'])->name('leads.meetings');
        Route::get('lead/getleadmeetings/{id}', [App\Http\Controllers\LeadController::class, 'GetMeetingList'])->name('leads.meetinglist');

        Route::get('lead/demo-export', [\App\Http\Controllers\LeadController::class, 'export'])->name('leads.exportDemo');
        Route::post('lead/import', [\App\Http\Controllers\LeadController::class, 'importFile'])->name('leads.import');

        Route::post('premiumPaidByCustomer', [App\Http\Controllers\LeadController::class, 'updatePremiumPaidByCustomer'])->name('leads.updatePremiumPaidByCustomer');
        Route::post('customer-verify', [App\Http\Controllers\LeadController::class, 'customerVerify'])->name('customerVerify');
        Route::get('premium-paid-by-customer', [App\Http\Controllers\PremiumPaidController::class, 'index'])->name('permiumpaid');
        Route::post('get-premium-collection-user', [App\Http\Controllers\PremiumPaidController::class, 'getPremiumCollection'])->name('getPremiumCollection');
        Route::post('premium-verify', [App\Http\Controllers\PremiumPaidController::class, 'premiumVerify'])->name('premiumVerify');
    });

    Route::prefix('admin')->name('admin.')->group(function () {
        Route::get('seo-form', [App\Http\Controllers\SeoFormController::class, 'index'])->name('seoForm');
        Route::get('seo-form-create', [App\Http\Controllers\SeoFormController::class, 'create'])->name('seoForm.create');
        Route::post('seo-form/create', [App\Http\Controllers\SeoFormController::class, 'store'])->name('seoForm.store');
        Route::get('seo-form/edit/{id}', [App\Http\Controllers\SeoFormController::class, 'edit'])->name('seoForm.edit');
        Route::post('seo-form/edit/{id}', [App\Http\Controllers\SeoFormController::class, 'update'])->name('seoForm.update');
        Route::delete('seo-form/delete', [App\Http\Controllers\SeoFormController::class, 'delete'])->name('seoForm.delete');
    });

    Route::middleware(['auth', 'access:create-policy'])->prefix('admin/policycategories')->name('admin.policycategories.')->group(function () {
        Route::resource('sub', \App\Http\Controllers\PolicySubCategoryController::class)->except('create', 'show');
        Route::resource('type', \App\Http\Controllers\PolicyTypeController::class)->except('create', 'show');
    });

    Route::middleware(['auth', 'access:create-product'])->prefix('admin')->name('admin.')->group(function () {
        Route::get('productList', [App\Http\Controllers\ProductController::class, 'index'])->name('product.list');
        Route::get('productDeletedList', [App\Http\Controllers\ProductController::class, 'trashedProductsList'])->name('product.deleted');
        Route::get('productDeletedList/{id}', [App\Http\Controllers\ProductController::class, 'restoreProduct'])->name('product.restore');
        Route::get('productCreate', [App\Http\Controllers\ProductController::class, 'create'])->name('product.create');
        Route::post('productCreate', [App\Http\Controllers\ProductController::class, 'store'])->name('product.store');
        Route::get('productEdit/{id}', [App\Http\Controllers\ProductController::class, 'edit'])->name('product.edit');
        Route::post('productEdit/{id}', [App\Http\Controllers\ProductController::class, 'update'])->name('product.update');
        Route::delete('productDelete/{id}', [App\Http\Controllers\ProductController::class, 'destroy'])->name('product.destroy');
        Route::patch('product-update-status', [App\Http\Controllers\ProductController::class, 'updateProductStatus'])->name('product.status');

        //categories
        Route::get('category', [ProductCategoriesController::class, 'index'])->name('category');
        Route::get('category/create', [ProductCategoriesController::class, 'create'])->name('category.create');
        Route::post('category/store', [ProductCategoriesController::class, 'store'])->name('category.store');
        Route::get('category/edit/{id}', [ProductCategoriesController::class, 'edit'])->name('category.edit');

resources/views/Backend/Type/index.blade.php
@extends('layouts.backend.containerlist')
@section('title')
Policy Types
@endsection
@section('dynamicdata')
<div class="box">

    <div class="box-header with-border c-btn-right d-flex-row ">
        <div class="justify-content-end list-group list-group-horizontal ">
            <button class="btn btn-primary c-primary-btn add-modal shadow-none mx-2" data-toggle="modal" data-target="#addNewUserModal">
                {{-- <img src="{{ asset('uploads/add-circle-16-Regular.svg') }}" alt="Add-icon"> --}}
                 &nbsp; Add New &nbsp;
            </button>
        </div>
    </div>

    {{-- <div class="box-header with-border d-flex">
        <a href="javascript:;" class="add-modal align-self-center justify-content-center">
            <button class="btn btn-primary shadow-none ">Add New Policy Type &nbsp;<i class="fa fa-plus-circle"></i></button>
        </a>
    </div> --}}
    <!-- /.box-header -->
    <div class="box-body">
        @include('layouts.backend.alert')
        <table id="example1" class="table table-bordered table-striped role-table policytype-table">
            <thead>
                <tr>
                    <th>SN</th>
                    <th>Policy Type</th>
                    <th class="dt-center">Status</th>
                    <th class="dt-center">Actions</th>
                </tr>
            </thead>
            <tbody id="tablebody">
                @foreach($types as $data)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $data->type }}</td>
                    <td class="dt-center">
                        @if($data->is_active == 1)
                        <small
                            class="label bg-green leads-status-btn leads-status-btn-active">Active</small>
                        @else
                        <small
                            class="label bg-red leads-status-btn leads-status-btn-inactive">Inactive</small>
                        @endif
                    </td>
                    <td class="justify-content-center">
                        <a href="javascript:;" title="Edit Policy Type"><button class="btn btn-primary btn-flat"
                                data-type_id="{{$data->id}}" data-policy_cat_id="{{$data->policy_cat_id}}"
                                data-subcat_id="{{$data->subcat_id}}" data-is_active="{{$data->is_active}}"
                                data-type="{{$data->type}}" data-toggle="modal" data-target="#editModal"><i
                                    class="fa fa-edit"></i></button></a>&nbsp;
                        <a href="javascript:;" title="Delete policytype" class="delete-policytype"
                            id="{{ $data->id }}"><button class="btn btn-danger btn-flat"><i
                                    class="fa fa-trash"></i></button></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->

<!-- Modal form to add a type -->
<div id="addModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header d-flex">
                <h4 class="modal-title">Add Policy Type</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form" method="POST"
                    action="{{ route('admin.policycategories.type.store') }}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label class="control-label" for="policy_cat_id">Policy Category</label>
                        <div class="">
                            <select class="form-control" name="policy_cat_id">
                                <option value="0" disabled selected>Select Policy Category</option>
                                @foreach($policy_categories as $policy_categorie)
                                <option value="{{ $policy_categorie->id }}">{{ $policy_categorie->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="subcat_id">Policy Sub Category</label>
                        <div class="">
                            <select class="form-control" name="subcat_id">
                                <option value="0" disabled selected>Select Policy Sub Category</option>
                                @foreach($policy_sub_categories as $policy_sub_categorie)
                                <option value="{{ $policy_sub_categorie->id }}">{{ $policy_sub_categorie->subcat_name }}
                                </option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="subcat_name">Policy Type:<span style="color: red;">
                                *</span></label>
                        <div class="">
                            <input type="text" class="form-control" name="type" autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="content">Status:</label>
                        <div class="">
                            <select name="is_active" class="form-control">
                                <option value="1">Active</option>
                                <option value="0">Inactive</option>
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer pt-2 pb-0 px-0">
                        <button type="button" class="btn btn-light shadow-none border-2 bg-transparent"
                            data-dismiss="modal">
                            <span class='glyphicon glyphicon-remove'></span> Close
                        </button>
                        <button type="submit" class="btn btn-primary add shadow-sm px-4 border-2 m-0">
                            <span id="" class='glyphicon'></span> Add
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="editModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header d-flex">
                <h4 class="modal-title">Edit Policy Type</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form" method="POST"
                    action="{{ route('admin.policycategories.type.update','type') }}">
                    {{ csrf_field() }}
                    {{ method_field('PATCH')}}
                    <input type="hidden" name="type_id" id="type_id" value="">
                    <div class="form-group">
                        <label class="control-label" for="policy_cat_id">Policy Category</label>
                        <div class="">
                            <select class="form-control" name="policy_cat_id" id="policy_cat_id">
                                <option value="0" disabled selected>Select Policy Category</option>
                                @foreach($policy_categories as $policy_categorie)
                                <option value="{{ $policy_categorie->id }}">{{ $policy_categorie->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="subcat_id">Policy Sub Category</label>
                        <div class="">
                            <select class="form-control" name="subcat_id" id="subcat_id">
                                <option value="0" disabled selected>Select Policy Sub Category</option>
                                @foreach($policy_sub_categories as $policy_sub_categorie)
                                <option value="{{ $policy_sub_categorie->id }}">{{ $policy_sub_categorie->subcat_name }}
                                </option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="subcat_name">Policy Type:<span style="color: red;">
                                *</span></label>
                        <div class="">
                            <input type="text" class="form-control" name="type" id="type" autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="content">Status:</label>
                        <div class="">
                            <select name="is_active" class="form-control">
                                <option value="1">Active</option>
                                <option value="0">Inactive</option>
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer pt-2 pb-0 px-0">
                        <button type="button" class="btn btn-light shadow-none border-2 bg-transparent"
                            data-dismiss="modal">
                            <span class='glyphicon glyphicon-remove'></span> Close
                        </button>
                        <button type="submit" class="btn btn-success add shadow-sm px-4 border-2 m-0">
                            <span id="" class='glyphicon'></span> Update
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('footer_js')
<script type="text/javascript">
    $(document).ready(function() {
        $(document).on('click', '.add-modal', function() {
            $('#addModal').modal('show');
        });
        $('#editModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget)
        var type = button.data('type')
        var type_id = button.data('type_id')
        var is_active = button.data('is_active')
      var policy_cat_id = button.data('policy_cat_id')
      var subcat_id = button.data('subcat_id')
      var modal = $(this)
      modal.find('.modal-body #type').val(type);
      modal.find('.modal-body #type_id').val(type_id);
      modal.find('.modal-body #is_active').val(is_active);
      modal.find('.modal-body #policy_cat_id').val(policy_cat_id);
      modal.find('.modal-body #subcat_id').val(subcat_id);
    });
});
</script>
<script type="text/javascript">
    $(document).ready(function() {
        var oTable = $('.policytype-table').dataTable();

        $('#tablebody').on('click', '.delete-policytype', function(e){
            e.preventDefault();
            $object = $(this);
            var id = $object.attr('id');
            new swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then(function(response) {
                if (response.isConfirmed == true) {
                $.ajax({
                    type: "DELETE",
                    url: "{{ url('/admin/policycategories/type/') }}"+"/"+id,
                    data: {
                        '_token': $('meta[name="csrf-token"]').attr('content')
                    },
                    beforeSend: function () {
                        $('#preloader').show();
                    },
                    dataType: 'json',
                    success: function(response){
                        $('#preloader').hide();
                        var nRow = $($object).parents('tr')[0];
                        oTable.fnDeleteRow(nRow);
                        new swal('success', response.message, 'success');
                    },
                    error: function(e){
                        $('#preloader').hide();
                        new swal('Oops...', 'Something went wrong!', 'error');
                    }
                });
                }
            }).catch(swal.noop);
        });
    });
</script>
@endsection